# Generated by Django 4.0.6 on 2022-07-21 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_slug_alter_post_content_alter_post_data_updated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(db_index=True, help_text='не более 200 символов', max_length=200),
        ),
    ]
